# Generated by Django 6.0.3 on 2026-04-26 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_login_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('slot_time', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed')], default='Booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
