# Generated by Django 6.0.3 on 2026-04-26 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_login_system', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('found_place', models.CharField(max_length=150)),
                ('date_found', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Matched', 'Matched'), ('Returned', 'Returned')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('last_seen_place', models.CharField(max_length=150)),
                ('date_lost', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Matched', 'Matched'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
