# Generated by Django 6.0.3 on 2026-04-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_login_system', '0004_reschedulerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('holiday_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RescheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('original_date', models.DateField()),
                ('new_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('class_date', models.DateField()),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('faculty_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Missed', 'Missed'), ('Rescheduled', 'Rescheduled')], default='Scheduled', max_length=20)),
            ],
        ),
    ]
