# Generated by Django 6.0.3 on 2026-04-26 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_login_system', '0006_room_subject_timeslot_generatedtimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('total_required_classes', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('class_date', models.DateField()),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Holiday', 'Holiday'), ('Rescheduled', 'Rescheduled')], default='Scheduled', max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_login_system.yearlysubject')),
            ],
        ),
    ]
