# Generated by Django 6.0.3 on 2026-04-26 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_login_system', '0007_yearlysubject_yearlytimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_class', models.CharField(max_length=100)),
                ('missed_date', models.DateField()),
                ('compensation_date', models.DateField()),
                ('compensation_slot', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('slot_1', models.CharField(max_length=100)),
                ('slot_2', models.CharField(max_length=100)),
                ('slot_3', models.CharField(max_length=100)),
                ('slot_4', models.CharField(max_length=100)),
                ('slot_5', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_name',
            field=models.CharField(max_length=100),
        ),
    ]
